### PR TITLE
Added Digital Devices (manufacturer), changed dvdbsky (corrections an…

### PR DESCRIPTION
**Pull request by mmajoor**
…d disabled)

Note: Distribution/options has 'dvbsky' disabled (did not compile)
Some errors for dvbsky in the script package have been addressed (not tested)

These Digital Devices sources are those where the manufacturer refers to:
http://support.digital-devices.eu/knowledgebase.php?article=152

Includes a future patch for the 4.6 kernel ... (directory rename needed for this)

### CODE REVIEW

**Comment by CvH** [comment]
I had tested it also but got it never working that it compiles for the specific kernel (it compiles every time for 4.4.0 -> modules not working). 
Did you have the hw to test if this is working ? Btw the unpack function is wrong (or over complicated) but this I could address later. Sadly I have squashed the packe for this driver - maybe I was also very near to get it working ;)

Btw there are no dvbsky changes - I know that it didn't work was just an test from today if it works ootb or not.

**Comment by mmajoor** [comment]
For the  https://github.com/DigitalDevices/dddvb/releases sources to work, you only need to set KDIR correct. Without it it uses the host systems kernel...

>  Btw the unpack function ..

I had to do some tweaking because the sources do not expand as 'digital_devices' but as 'dddvb' which is identical to the already existing Digital Devices package ...

> Did you have the hw to test if this is working ?

I have some Digital Device hardware here (Octopus CI V2, DuoFlex S2, DuoFlex C/T if I am not mistaken). Both the 'dddvb' and 'digital_devices' drivers seem to work.

**Comment by CvH** [comment]
@mmajoor great - btw the kdir didn't worked for me - always set to 4.4.0 which is not my root system nor LE ... no idea whats there wrong but if it works why not :)

**Comment by CvH** [comment]
@mmajoor https://github.com/CvH/LibreELEC.tv/commit/597b339a5b70393ffb38a7e94eb47c573ebd8bff

added an fixup for your commit where it shows the "right" dl of the package, tx for your help

btw I had `make KDIR=$(kernel_path)` what works at every other driver so far ;D

**Pull request merged**
